services:
  v2v_web_app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - OLLAMA_HOST=https://ollama.irc-enter.tech
    networks:
      - internal-shared

networks:
  internal-shared: