services:
  v2v_web_app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - OLLAMA_HOST=http://ollama-api:11434
    volumes:
      - ./app:/app
    networks:
      - internal-shared
    deploy:
      resources:
        limits:
          memory: 2G

networks:
  internal-shared: